package modelo;
// Generated 13 ene 2025, 13:01:47 by Hibernate Tools 6.5.1.Final

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.swing.JOptionPane;

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

import hibernate.HibernateUtil;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int id;
	private Tipos tipos;
	private String email;
	private String username;
	private String password;
	private String nombre;
	private String apellidos;
	private String dni;
	private String direccion;
	private Integer telefono1;
	private Integer telefono2;
	private byte[] argazkia;
	private Set matriculacioneses = new HashSet(0);
	private Set reunionesesForProfesorId = new HashSet(0);
	private Set reunionesesForAlumnoId = new HashSet(0);
	private Set horarioses = new HashSet(0);

	public Users() {
	}

	public Users(String username, String password) {
		this.username = username;
		this.password = password;
		
	}
	public Users(int id, Tipos tipos) {
		this.id = id;
		this.tipos = tipos;
	}

	public Users(int id, Tipos tipos, String email, String username, String password, String nombre, String apellidos,
			String dni, String direccion, Integer telefono1, Integer telefono2, byte[] argazkia, Set matriculacioneses,
			Set reunionesesForProfesorId, Set reunionesesForAlumnoId, Set horarioses) {
		this.id = id;
		this.tipos = tipos;
		this.email = email;
		this.username = username;
		this.password = password;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.direccion = direccion;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.argazkia = argazkia;
		this.matriculacioneses = matriculacioneses;
		this.reunionesesForProfesorId = reunionesesForProfesorId;
		this.reunionesesForAlumnoId = reunionesesForAlumnoId;
		this.horarioses = horarioses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Tipos getTipos() {
		return this.tipos;
	}

	public void setTipos(Tipos tipos) {
		this.tipos = tipos;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Integer getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(Integer telefono1) {
		this.telefono1 = telefono1;
	}

	public Integer getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(Integer telefono2) {
		this.telefono2 = telefono2;
	}

	public byte[] getArgazkia() {
		return this.argazkia;
	}

	public void setArgazkia(byte[] argazkia) {
		this.argazkia = argazkia;
	}

	public Set getMatriculacioneses() {
		return this.matriculacioneses;
	}

	public void setMatriculacioneses(Set matriculacioneses) {
		this.matriculacioneses = matriculacioneses;
	}

	public Set getReunionesesForProfesorId() {
		return this.reunionesesForProfesorId;
	}

	public void setReunionesesForProfesorId(Set reunionesesForProfesorId) {
		this.reunionesesForProfesorId = reunionesesForProfesorId;
	}

	public Set getReunionesesForAlumnoId() {
		return this.reunionesesForAlumnoId;
	}

	public void setReunionesesForAlumnoId(Set reunionesesForAlumnoId) {
		this.reunionesesForAlumnoId = reunionesesForAlumnoId;
	}

	public Set getHorarioses() {
		return this.horarioses;
	}

	public void setHorarioses(Set horarioses) {
		this.horarioses = horarioses;
	}

	
	@Override
	public String toString() {
		return "Users [id=" + id + ", tipos=" + tipos + ", email=" + email + ", username=" + username + ", password="
				+ password + ", nombre=" + nombre + ", apellidos=" + apellidos + ", dni=" + dni + ", direccion="
				+ direccion + ", telefono1=" + telefono1 + ", telefono2=" + telefono2 + ", argazkia="
				+ Arrays.toString(argazkia) + ", matriculacioneses=" + matriculacioneses + ", reunionesesForProfesorId="
				+ reunionesesForProfesorId + ", reunionesesForAlumnoId=" + reunionesesForAlumnoId + ", horarioses="
				+ horarioses + "]";
	}

	//Consulta para verificar que el usuario introducido es de tipo profesor
	
	public int insertarLogin(String usuario, String contrasena) {
		
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Users where username = '" + usuario + "' AND password = '" + contrasena
				+ "' AND tipos.name = 'profesor' ";
		Query q = session.createQuery(hql);
		Users usuarioComprobado = (Users) q.uniqueResult();
		if (usuarioComprobado == null) {
			return 0;
		} else {
			return usuarioComprobado.id;
		}
	}
	
	//Obtencion del horario del profesor mediante la id
	
	public String[][] getHorarioById(int idProfesor) {
		String[][] horarioProfesor= { { "08:00-09:00", "", "", "", "", "", "", "" }, { "09:00-10:00", "", "", "", "", "", "", "" },
				{ "10:00-11:00", "", "", "", "", "", "", "" }, { "11:00-12:00", "", "", "", "", "", "", "" },
				{ "12:00-13:00", "", "", "", "", "", "", "" } };

		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Horarios where users = " + idProfesor + " ";
		Query q = session.createQuery(hql);
		List<?> filas = q.list();

		for (int i = 0; i < filas.size(); i++) {
			Horarios horario = (Horarios) filas.get(i);
			int dia = conseguirDia(horario.getId().getDia());
			int hora = Integer.parseInt(horario.getId().getHora());
			horarioProfesor[hora - 1][dia] = horario.getModulos().getNombre();
		}

		return horarioProfesor;
	}

	//Obtener los dias de la BD
	
	private int conseguirDia(String string) {
		// TODO Auto-generated method stub
		int dia = 0;
		if (string.equals("L/A")) {
			dia = 1;
		} else if (string.equals("M/A")) {
			dia = 2;
		} else if (string.equals("X")) {
			dia = 3;
		} else if (string.equals("J/O")) {
			dia = 4;
		} else if (string.equals("V/O")) {
			dia = 5;
		} else if (string.equals("S/L")) {
			dia = 6;
		} else if (string.equals("D/I")) {
			dia = 7;
		}
		return dia;
	}
	
	//Consulta para el comboBox en Otros Horarios
	
	public String[] getProfesores(int idLogueado) {
		
	    String[] nombresProfesores = new String[0];
	 
	    SessionFactory sesion = HibernateUtil.getSessionFactory();
	    Session session = sesion.openSession();

	    try {
	        // Consulta HQL para obtener profesores excepto el usuario logueado	
	        String hql = "from Users where tipos.name = 'profesor' and id != :idLogueado";
	        Query query = session.createQuery(hql);
	        query.setParameter("idLogueado", idLogueado);
	        
	        List<Users> profesores = query.list();

	        // Convertir los nombres de los profesores a un array de Strings   
	        nombresProfesores = new String[profesores.size()];
	        
	        for (int i = 0; i < profesores.size(); i++) {
	            nombresProfesores[i] = profesores.get(i).getNombre();
	        }
	    } catch (Exception e) {
	        e.printStackTrace();
	    } finally {
	        session.close();
	    }

	    return nombresProfesores;
	}

	//Obtencion del Id del profesor seleccionado
	
	public int obtenerIdProfesor(String nombreProfesor) {
		
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Users where username = '" + nombreProfesor + "' AND tipos.name = 'profesor' ";
		Query q = session.createQuery(hql);
		Users idProfesor = (Users) q.uniqueResult();
		if (idProfesor == null) {
			return 0;
		} else {
			return idProfesor.id;
		}
	}

	
	
	
		
}
